[book]
authors = ["Jordan Hoare"]
language = "en"
multilingual = false
src = "src"
title = "Mythbound"

[output.html]
additional-js = []
default-theme = "dark"
preferred-dark-theme = "ayu"
no-section-label = true
git-repository-url = "https://tibia-oce.github.io/"
git-repository-icon = "fa-github"
git-branch = "master"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
copyable = false

[output.html.search]
limit-results = 15

[[chapter]]
name = "Infrastructure"
path = "infrastructure/README.md"
